export const SIGN_UP = "SIGN_UP";
export const MESSAGE = "MESSAGE";
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const ARTICLES_FETCHED = "ARTICLES_FETCHED"
export const ARTICLES_SHOWED = "ARTICLES_SHOWED"
export const ARTICLE_CREATED = "ARTICLE_CREATED"
export const ARTICLE_UPDATED = "ARTICLE_UPDATED"
export const ARTICLE_DELETED = "ARTICLE_DELETED"
